Change to always restart
AudiusProject/audius-docker-compose pull request #134
Opened 2022-10-31 19:40 UTC by cheran-senthil

### Description
Change to always restart with autoheal

2022-10-31 19:43 UTC, dmanjunath approved these changes
i see what happened here. discovery had all this stuff but content never did.

2022-10-31 19:43 UTC, cheran-senthil commented
Yes, exactly

2022-10-31 19:45 UTC, SidSethi approved these changes
nice find!

2022-11-02 16:15 UTC, dmanjunath requested changes

2022-11-02 16:15 UTC, dmanjunath commented on common-services.yml
> +    restart: always
lets keep this in content node only. this is due to a content node limitation. if redis restarts the server also needs to restart

2022-11-03 15:45 UTC, merged