PLAT-750: non signer acdc config
AudiusProject/audius-docker-compose pull request #219
Opened 2023-03-05 21:47 UTC by alecsavvy

### Description
Adds a new config option when deploying the chain `--isminer`. 

When set to true (default) this will unset the false flag if it previously exists in whatever .env file is used. The node will then default to config.cfg and use what's in there on a redeploy.

When set `--ismining=False` the isMining env var is set to false and the node will deploy in non sealing mode.
docs: https://docs.nethermind.io/nethermind/ethereum-client/configuration/init

The effect of this is now nodes that are deployed as non signers will correctly report healthy instead of of attempting to seal blocks and fail for eternity.

Tested on prod ACDC

2023-03-06 17:44 UTC, isaacsolo approved these changes

2023-03-06 17:46 UTC, isaacsolo requested changes
still hesitant about merging this because i think it might add complexity. if our sandbox nodes are the only ones that would want this, it get confusing on knowing whether a node is supposed to be able to mine or not (config.cfg says IsMining true but there happens to be an override env for NETHERMIND_INITCONFIG_ISMINING false. most cases we just want a sandbox to resemble prod. just changing the config.cfg to false seems more obvious? like maybe leave a comment on it that says switch to false if you want to see a healthy chain for non signer.

2023-03-06 17:49 UTC, isaacsolo commented on audius-cli
> +        print("removing ismining env var in favor of config.cfg")
by default, we will see this log when chain is launched?

unset_key

2023-03-06 17:50 UTC, isaacsolo commented on audius-cli
> +        dotenv.unset_key(env, "NETHERMIND_INITCONFIG_ISMINING")
what happens if this key doesn't exist?

2023-03-06 21:03 UTC, cheran-senthil commented
Please tag me in these PRs that touch audius-cli 👀

Currently, if this bricks, auto upgrade bricks and that is a massive hassle to deal with

2023-03-06 21:05 UTC, cheran-senthil commented
This looks, dangerous 👀 you shouldn't be changing audius-cli for this kind of change, I agree much with Isaac here

2023-03-07 16:38 UTC, cheran-senthil requested changes
Use set config

2023-03-13 18:13 UTC, alecsavvy commented
closing as all nodes should be signers outside of dev / debug machines

2023-03-13 18:13 UTC, closed without merging