Split out discovery provider into two containers
AudiusProject/audius-docker-compose pull request #69
Opened 2022-09-12 15:45 UTC by cheran-senthil

2022-09-12 16:45 UTC, cheran-senthil commented
https://github.com/AudiusProject/audius-protocol/pull/3853/files

2022-09-12 16:51 UTC, joaquincasares requested changes

2022-09-12 16:51 UTC, joaquincasares commented on discovery-provider/docker-compose.yml
> +    image: audius/discovery-provider:${TAG:-c54dc44721ad3c8352f0cec56b94002cffe9512a}
Let's use `container_name: indexer` so that ELK can grab logs.

2022-09-12 16:51 UTC, joaquincasares commented on discovery-provider/docker-compose.yml
> +    image: audius/discovery-provider:${TAG:-c54dc44721ad3c8352f0cec56b94002cffe9512a}
Changes have already been made, built, and pushed to Docker Hub via this commit for the Filebeat container:

* https://github.com/AudiusProject/audius-protocol/pull/3846/commits/c3a1c526e62b482c3be12db8d818de989fabfe5e

2022-09-12 17:02 UTC, joaquincasares approved these changes

2022-09-12 18:29 UTC, jowlee approved these changes

2022-09-13 15:27 UTC, cheran-senthil commented
This stopped working on stage DP2, will merge after figuring this out

2022-10-11 00:42 UTC, raymondjacobson commented
@cheran-senthil we can probs merge now right?

2022-10-11 18:15 UTC, merged